<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Phalcon Blog</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100 mr-5" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
        </div>

    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-fixed pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/admin">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap 
      align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Blogs</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2" float-left>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>
                </div>

                <main class='col col-md-12'>
                    <div class="album py-1 bg-light">
                        <div class="container overflow-hidden">
                        </div>
                        <div class="container bg-dark text-dark">

                            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-1">
                                <?php
                                $html = "";
                                foreach ($blogs as $row) {
                                    // $result = substr($row->content, 0, 100);
                                    $html .= "<div class='col col-md-6 justify-content-between mt-2 mb-2'>
                    <div class='card shadow-sm'>
                    <div class='card-body text-center'>
                    <p class='card-text text-dark font-weight-bold text-uppercase'>$row->title</p>
                    <div class='justify-content-between align-items-center'>
                    <span style='display: inline'>$row->content</span>
                    <form action='/admin/editblog' method='post' style='display:inline'>
                    <input type='hidden' name='blogid' value='$row->id'>
                    <input name='readmore' type='hidden' href='/admin/readmore' class='text-muted' style= 'border:none; display: inline; background-color: white' value='...Read More'/>
                    <p class='text-muted'>Date Created: $row->time</p>
                    <input type='submit' name='editBlog' class='btn btn-primary' value='Edit'>
                    
                    </form>
                    <form method ='POST' action='/admin/delete' style='display:inline'>
                    <input type='hidden' name='blogid' value='$row->id'>
                    <input type='submit' name='dltBlog' class='btn btn-danger' value='Delete'>
                    </form>
                    </div>
                    </div>
                    </div>
                    </div>";
                                }

                                echo $html;

                                ?>


                            </div>
                        </div>

                    </div>
        </div>
        </main>